defaults:
  - generator: mimo_unet_pure
  - discriminator: n_layers
  - dataset: GOPRO
  - data: srgan
  - wandb: config
  - model_checkpoint_save: model_checkpoint_config
  - trainer: one_trainer
  - adv_loss: ragan_ls
  - generator_basic_loss: losses
  - optimizer: optimizer_config
  - scheduler: plateau
