defaults:
  - generator: mimo_fpn
  - discriminator: srgan
  - dataset: GOPRO
  - data: srgan
  - wandb: config
  - model_checkpoint_save: model_checkpoint_config
  - trainer: one_trainer
  - adv_loss: wgan_gp
  - generator_basic_loss: losses
  - optimizer: optimizer_config
  - scheduler: plateau

#general:
#  generator: srgan
#  discriminator: omry
#  pass: secret